server :
   port: 8081

spring:
  datasource:
     url       : jdbc:mysql://mysql:3306/sampledb
     username  : userD17
     password  : BDWacpl3Y5itPRI0
     driver-class-name : com.mysql.cj.jdbc.Driver
  application:
    name: movie-service
    
jpa:
   database-platform : org.hibernate.dialect.MySQL8Dailect
   
   hibernate:
        ddl-auto : update
   
