apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: movie-service
  name: movie-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-service
  strategy: {}
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
      - image: docker.io/ssuram1/movie-service
        name: movie-service
        volumeMounts:
          - mountPath: /app/config
            name: movie-service-config
        env:
          - name:  SPRING_CONFIG_LOCATION  
            value: /app/config/ 
      volumes:
        - name: movie-service-config
          configMap:
           name: movie-service-config
status: {}
